# springboot整合postgres连接配制
spring:
  redis:
    database: 4
    host: 111.229.204.101
    port: 63790
    password: 1qaz2wsx
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  datasource:
    url:  jdbc:mysql://47.100.216.66:3306/bsd_asy?characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: Bsd@2019
    driver-class-name: com.mysql.jdbc.Driver
  #解决整合后报的一个错：<aused by: java.sql.SQLFeatureNotSupportedException: 这个 org.postgresql.jdbc.PgConnection.createClob() 方法尚未被实作。>
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#mybatis-plus整合，加了表前缀的全局配制，加了类中与表中驼峰的映射，不加会查不出数据，因无法做表与类字段映射
mybatis-plus:
  global-config:
    db-config:
      table-prefix: template.
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.bsd.say.entities
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.bsd.say.mapper: debug

server:
  port: 8082

award:
  rule: 5
  amount: 2

wechat:
  aesKey: r4cbRuIfbbnTIgJoQE33vJACJuoioZ5pRAhumITsP8O
  componentToken: bosidengqixi
  appId: wx4f4363086a52e92c
  componentAppId: wx474350bcaea2d745
  componentAppSecret: 947dc4a4500adf09fc5ee31b132742e5
  getComponentAccessTokenUrl: https://api.weixin.qq.com/cgi-bin/component/api_component_token
  getAccessTokenUrl: https://api.weixin.qq.com/sns/oauth2/component/access_token?appid=
  getUnionIdUrl: https://api.weixin.qq.com/sns/userinfo?access_token=
  getWxUserInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info?access_token=
  getTicketUrl: https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=


bsd:
  tokenkey: BOSIDENG
  sendSource: BRAND_VERIFY_CODE
  verifySMSCodeUrl: http://wxitf.bsd.cn/BSD_WXAPP/sysWeChat/verifySMSCode?token=
  addCouponUrl: http://wxitf.bsd.cn/BSD_WXAPP/miniProgram/addCoupon?token=
### 上传文件路径
#upload:
#  excel:
#    path: /Users/yaoyao.zhu/Documents/
